# Generated by Django 5.2.8 on 2025-11-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('NOTE', 'Note'), ('SLIDE', 'Slide'), ('PAST', 'Past Question'), ('EBOOK', 'Ebook')], max_length=10)),
                ('pdf', models.FileField(upload_to='materials/pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='students.course')),
            ],
        ),
    ]
